name: rapid
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  path: ^1.8.0
  meta: ^1.8.0
  mime: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dio: ^4.0.6
  http: ^0.13.5
